Map<String, dynamic> currencyCountryMap = {
  "AFN": "Afghanistan",
  "ALL": "Albania",
  "DZD": "Algeria",
  "AOA": "Angola",
  "ARS": "Argentina",
  "AMD": "Armenia",
  "AUD": "Australia",
  "AZN": "Azerbaijan",
  "BSD": "Bahamas",
  "BHD": "Bahrain",
  "BDT": "Bangladesh",
  "BBD": "Barbados",
  "BYN": "Belarus",
  "BZD": "Belize",
  "BMD": "Bermuda",
  "BTN": "Bhutan",
  "BOB": "Bolivia",
  "BAM": "Bosnia and Herzegovina",
  "BWP": "Botswana",
  "BRL": "Brazil",
  "BND": "Brunei",
  "BGN": "Bulgaria",
  "BIF": "Burundi",
  "KHR": "Cambodia",
  "CAD": "Canada",
  "CVE": "Cape Verde",
  "KYD": "Cayman Islands",
  "XAF": "Central African Republic",
  "CLP": "Chile",
  "CNY": "China",
  "COP": "Colombia",
  "CRC": "Costa Rica",
  "HRK": "Croatia",
  "CUP": "Cuba",
  "CZK": "Czech Republic",
  "DKK": "Denmark",
  "DJF": "Djibouti",
  "DOP": "Dominican Republic",
  "EGP": "Egypt",
  "ETB": "Ethiopia",
  "EUR": "European Union",
  "FJD": "Fiji",
  "GMD": "Gambia",
  "GEL": "Georgia",
  "GHS": "Ghana",
  "GTQ": "Guatemala",
  "GNF": "Guinea",
  "GYD": "Guyana",
  "HTG": "Haiti",
  "HNL": "Honduras",
  "HKD": "Hong Kong",
  "HUF": "Hungary",
  "ISK": "Iceland",
  "INR": "India",
  "IDR": "Indonesia",
  "IRR": "Iran",
  "IQD": "Iraq",
  "ILS": "Israel",
  "JMD": "Jamaica",
  "JPY": "Japan",
  "JOD": "Jordan",
  "KZT": "Kazakhstan",
  "KES": "Kenya",
  "KWD": "Kuwait",
  "KGS": "Kyrgyzstan",
  "LAK": "Laos",
  "LBP": "Lebanon",
  "LSL": "Lesotho",
  "LRD": "Liberia",
  "LYD": "Libya",
  "MOP": "Macau",
  "MKD": "North Macedonia",
  "MGA": "Madagascar",
  "MWK": "Malawi",
  "MYR": "Malaysia",
  "MVR": "Maldives",
  "MRO": "Mauritania",
  "MUR": "Mauritius",
  "MXN": "Mexico",
  "MDL": "Moldova",
  "MNT": "Mongolia",
  "MAD": "Morocco",
  "MMK": "Myanmar",
  "NAD": "Namibia",
  "NPR": "Nepal",
  "NZD": "New Zealand",
  "NIO": "Nicaragua",
  "NGN": "Nigeria",
  "NOK": "Norway",
  "OMR": "Oman",
  "PKR": "Pakistan",
  "PAB": "Panama",
  "PGK": "Papua New Guinea",
  "PYG": "Paraguay",
  "PEN": "Peru",
  "PHP": "Philippines",
  "PLN": "Poland",
  "QAR": "Qatar",
  "RON": "Romania",
  "RUB": "Russia",
  "RWF": "Rwanda",
  "SAR": "Saudi Arabia",
  "RSD": "Serbia",
  "SGD": "Singapore",
  "SBD": "Solomon Islands",
  "ZAR": "South Africa",
  "KRW": "South Korea",
  "LKR": "Sri Lanka",
  "SDG": "Sudan",
  "SRD": "Suriname",
  "SEK": "Sweden",
  "CHF": "Switzerland",
  "TWD": "Taiwan",
  "THB": "Thailand",
  "TRY": "Turkey",
  "UGX": "Uganda",
  "UAH": "Ukraine",
  "AED": "United Arab Emirates",
  "GBP": "United Kingdom",
  "USD": "United States",
  "UYU": "Uruguay",
  "UZS": "Uzbekistan",
  "VUV": "Vanuatu",
  "VND": "Vietnam",
  "XOF": "West African CFA",
  "YER": "Yemen",
  "ZMW": "Zambia",
  "ZWL": "Zimbabwe",
};