Map<String, dynamic> currencyCountryMap = {
  "AFN": {"country": "Afghanistan", "symbol": "؋"},
  "ALL": {"country": "Albania", "symbol": "L"},
  "DZD": {"country": "Algeria", "symbol": "د.ج"},
  "AOA": {"country": "Angola", "symbol": "Kz"},
  "ARS": {"country": "Argentina", "symbol": "\$"},
  "AMD": {"country": "Armenia", "symbol": "֏"},
  "AUD": {"country": "Australia", "symbol": "\$"},
  "AZN": {"country": "Azerbaijan", "symbol": "₼"},
  "BSD": {"country": "Bahamas", "symbol": "\$"},
  "BHD": {"country": "Bahrain", "symbol": ".د.ب"},
  "BDT": {"country": "Bangladesh", "symbol": "৳"},
  "BBD": {"country": "Barbados", "symbol": "\$"},
  "BYN": {"country": "Belarus", "symbol": "Br"},
  "BZD": {"country": "Belize", "symbol": "\$"},
  "BMD": {"country": "Bermuda", "symbol": "\$"},
  "BTN": {"country": "Bhutan", "symbol": "Nu."},
  "BOB": {"country": "Bolivia", "symbol": "Bs."},
  "BAM": {"country": "Bosnia and Herzegovina", "symbol": "KM"},
  "BWP": {"country": "Botswana", "symbol": "P"},
  "BRL": {"country": "Brazil", "symbol": "R\$"},
  "BND": {"country": "Brunei", "symbol": "\$"},
  "BGN": {"country": "Bulgaria", "symbol": "лв"},
  "BIF": {"country": "Burundi", "symbol": "Fr"},
  "KHR": {"country": "Cambodia", "symbol": "៛"},
  "CAD": {"country": "Canada", "symbol": "\$"},
  "CVE": {"country": "Cape Verde", "symbol": "Esc"},
  "KYD": {"country": "Cayman Islands", "symbol": "\$"},
  "XAF": {"country": "Central African Republic", "symbol": "CFA"},
  "CLP": {"country": "Chile", "symbol": "\$"},
  "CNY": {"country": "China", "symbol": "¥"},
  "COP": {"country": "Colombia", "symbol": "\$"},
  "CRC": {"country": "Costa Rica", "symbol": "₡"},
  "HRK": {"country": "Croatia", "symbol": "kn"},
  "CUP": {"country": "Cuba", "symbol": "₱"},
  "CZK": {"country": "Czech Republic", "symbol": "Kč"},
  "DKK": {"country": "Denmark", "symbol": "kr"},
  "DJF": {"country": "Djibouti", "symbol": "Fdj"},
  "DOP": {"country": "Dominican Republic", "symbol": "RD\$"},
  "EGP": {"country": "Egypt", "symbol": "ج.م"},
  "ETB": {"country": "Ethiopia", "symbol": "Br"},
  "EUR": {"country": "European Union", "symbol": "€"},
  "FJD": {"country": "Fiji", "symbol": "\$"},
  "GMD": {"country": "Gambia", "symbol": "D"},
  "GEL": {"country": "Georgia", "symbol": "ლ"},
  "GHS": {"country": "Ghana", "symbol": "¢"},
  "GTQ": {"country": "Guatemala", "symbol": "Q"},
  "GNF": {"country": "Guinea", "symbol": "Fr"},
  "GYD": {"country": "Guyana", "symbol": "\$"},
  "HTG": {"country": "Haiti", "symbol": "G"},
  "HNL": {"country": "Honduras", "symbol": "L"},
  "HKD": {"country": "Hong Kong", "symbol": "\$"},
  "HUF": {"country": "Hungary", "symbol": "Ft"},
  "ISK": {"country": "Iceland", "symbol": "kr"},
  "INR": {"country": "India", "symbol": "₹"},
  "IDR": {"country": "Indonesia", "symbol": "Rp"},
  "IRR": {"country": "Iran", "symbol": "﷼"},
  "IQD": {"country": "Iraq", "symbol": "د.ع"},
  "ILS": {"country": "Israel", "symbol": "₪"},
  "JMD": {"country": "Jamaica", "symbol": "\$"},
  "JPY": {"country": "Japan", "symbol": "¥"},
  "JOD": {"country": "Jordan", "symbol": "د.ا"},
  "KZT": {"country": "Kazakhstan", "symbol": "₸"},
  "KES": {"country": "Kenya", "symbol": "KSh"},
  "KWD": {"country": "Kuwait", "symbol": "د.ك"},
  "KGS": {"country": "Kyrgyzstan", "symbol": "сом"},
  "LAK": {"country": "Laos", "symbol": "₭"},
  "LBP": {"country": "Lebanon", "symbol": "ل.ل."},
  "LSL": {"country": "Lesotho", "symbol": "M"},
  "LRD": {"country": "Liberia", "symbol": "\$"},
  "LYD": {"country": "Libya", "symbol": "د.ل"},
  "MOP": {"country": "Macau", "symbol": "P"},
  "MKD": {"country": "North Macedonia", "symbol": "ден"},
  "MGA": {"country": "Madagascar", "symbol": "Ar"},
  "MWK": {"country": "Malawi", "symbol": "MK"},
  "MYR": {"country": "Malaysia", "symbol": "RM"},
  "MVR": {"country": "Maldives", "symbol": "Rf"},
  "MRO": {"country": "Mauritania", "symbol": "UM"},
  "MUR": {"country": "Mauritius", "symbol": "₨"},
  "MXN": {"country": "Mexico", "symbol": "\$"},
  "MDL": {"country": "Moldova", "symbol": "L"},
  "MNT": {"country": "Mongolia", "symbol": "₮"},
  "MAD": {"country": "Morocco", "symbol": "د.م."},
  "MMK": {"country": "Myanmar", "symbol": "K"},
  "NAD": {"country": "Namibia", "symbol": "\$"},
  "NPR": {"country": "Nepal", "symbol": "रु"},
  "NZD": {"country": "New Zealand", "symbol": "\$"},
  "NIO": {"country": "Nicaragua", "symbol": "C\$"},
  "NGN": {"country": "Nigeria", "symbol": "₦"},
  "NOK": {"country": "Norway", "symbol": "kr"},
  "OMR": {"country": "Oman", "symbol": "ر.ع."},
  "PKR": {"country": "Pakistan", "symbol": "₨"},
  "PAB": {"country": "Panama", "symbol": "B/."},
  "PGK": {"country": "Papua New Guinea", "symbol": "K"},
  "PYG": {"country": "Paraguay", "symbol": "₲"},
  "PEN": {"country": "Peru", "symbol": "S/."},
  "PHP": {"country": "Philippines", "symbol": "₱"},
  "PLN": {"country": "Poland", "symbol": "zł"},
  "QAR": {"country": "Qatar", "symbol": "ر.ق."},
  "RON": {"country": "Romania", "symbol": "RON"},
  "RUB": {"country": "Russia", "symbol": "₽"},
  "RWF": {"country": "Rwanda", "symbol": "Fr"},
  "SAR": {"country": "Saudi Arabia", "symbol": "ر.س."},
  "RSD": {"country": "Serbia", "symbol": "дин"},
  "SGD": {"country": "Singapore", "symbol": "\$"},
  "SBD": {"country": "Solomon Islands", "symbol": "\$"},
  "ZAR": {"country": "South Africa", "symbol": "R"},
  "KRW": {"country": "South Korea", "symbol": "₩"},
  "LKR": {"country": "Sri Lanka", "symbol": "රු"},
  "SDG": {"country": "Sudan", "symbol": "ج.س."},
  "SRD": {"country": "Suriname", "symbol": "\$"},
  "SEK": {"country": "Sweden", "symbol": "kr"},
  "CHF": {"country": "Switzerland", "symbol": "CHF"},
  "TWD": {"country": "Taiwan", "symbol": "NT\$"},
  "THB": {"country": "Thailand", "symbol": "฿"},
  "TRY": {"country": "Turkey", "symbol": "₺"},
  "UGX": {"country": "Uganda", "symbol": "USh"},
  "UAH": {"country": "Ukraine", "symbol": "₴"},
  "AED": {"country": "United Arab Emirates", "symbol": "د.إ"},
  "GBP": {"country": "United Kingdom", "symbol": "£"},
  "USD": {"country": "United States", "symbol": "\$"},
  "UYU": {"country": "Uruguay", "symbol": "\$"},
  "UZS": {"country": "Uzbekistan", "symbol": "сум"},
  "VUV": {"country": "Vanuatu", "symbol": "Vt"},
  "VND": {"country": "Vietnam", "symbol": "₫"},
  "XOF": {"country": "West African CFA", "symbol": "CFA"},
  "YER": {"country": "Yemen", "symbol": "﷼"},
  "ZMW": {"country": "Zambia", "symbol": "ZK"},
  "ZWL": {"country": "Zimbabwe", "symbol": "Z\$"},
};
